#!/bin/bash

LOADER=hex/loader-39e3671-01Dec2023.hex

while [ true ]
do
	make read > /dev/null 2> /dev/null

	while [ $? -ne 0 ]
	do
		echo -n .
		make read > /dev/null 2> /dev/null
	done

	echo -e "\n\033[1;33mProgramming\033[0m\n"
	espeak "Programming"
	make fuse
	make firmware HEX=$LOADER

	if [ $? -eq 0 ]
	then 
		echo -e "\033[0;32mComplete\033[0m\n"
		espeak "Complete"
	else 
		echo -e "\033[0;31mFailed\033[0m\n"
		espeak "Failed"
	fi
	
	sleep 1

done
